name: Nov치 hl치코ka
description: Navrhni hl치코ku ktor치 v appke ch칳ba a prid치me ju
title: "[SOUND]: "
labels: ["content"]
assignees:
  - mpilnan
body:
  - type: textarea
    id: which-sound
    attributes:
      label: Ktor치 hl치코ka?
      description: Pop칤코 hl치코ku ktor칰 by sme mali prida콘. Pre viacero hl치코ok vytvor pros칤m viacero 쬴adost칤.
      placeholder: Prep치캜te 쬰 me코k치m, meral som si...
    validations:
      required: true
  - type: dropdown
    id: movie
    attributes:
      label: Z ktor칠ho filmu je?
      description: Pravdepodobne budeme vedie콘, ale rad코ej vyber 游땐
      options:
        - Dano Drevo a Tajomn치 komnata
        - Dano Drevo a Turnaj Mekyho 콯birku
        - 'In칠 video (nap칤코 do pol칤캜ka vy코코ie, aj s odkazom na video)'
    validations:
      required: true
  - type: input
    id: time-code
    attributes:
      label: 캛as, v ktorom hl치코ka zaznie
      description: 캛칤m presnej코ie, t칳m lep코ie. Ide치lne 캜asov칳 k칩d z videa, pr칤padne aspo켿 v ktorej 캜asti filmu.
    validations:
      required: true